[tool.black]
line-length = 120
[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true
[tool.ruff]
line-length=120
ignore=["E401", "F401"]
[tool.ruff.per-file-ignores]
"test/test.py" = ["E402"]
[mypy]
cache_dir = "/tmp/mypy-cache"
